#!/bin/bash
set -eu

source /usr/share/yunohost/helpers

ynh_script_progression --message="Unregistering services from YunoHost..." --weight=1
yunohost service remove "$app-broker" || true
yunohost service remove "$app-livekit" || true

ynh_script_progression --message="Removing armada-av systemd services..." --weight=1
ynh_config_remove_systemd "$app-broker"
ynh_config_remove_systemd "$app-livekit"

ynh_script_progression --message="Removing armada-av Nginx configuration..." --weight=1
ynh_config_remove_nginx

ynh_script_progression --message="Removing armada-av files..." --weight=1
ynh_safe_rm "$install_dir"

ynh_script_progression --message="Armada AV removal complete" --last
